# ref: http://docs.travis-ci.com/user/build-configuration

language: cpp
compiler:
    - gcc

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-8
    env:
        - CC=gcc-8
        - CXX=g++-8

before_install:
    - sudo apt-get install -qq cmake
    - wget "http://www.lua.org/ftp/lua-5.3.5.tar.gz" && tar xzf lua-5.3.5.tar.gz && cd lua-5.3.5 && sudo make linux test install;

install:
    - cd $TRAVIS_BUILD_DIR
    - sudo make buildfbb
    - make all

script:
    - make test
